cors:
  configuration: '{"origins": ["*"], "methods": ["*"]}'
info:
  properties:
    environment: local
logging:
  level:
    root: INFO
    it:
      gov:
        pagopa: DEBUG
rendicontazioni:
  filePath: /mnt/firmatore/${ENV:local}/SID-Flussi-e-bollo/SID_cartelle/file_da_predisporre/
