microservice-chart:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-mbd
    tag: "0.1.0-1-upd-helm-deploy"
    pullPolicy: Always
  livenessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  readinessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 12345 #jmx-exporter
    - 8080
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weuprod.nodo.internal.platform.pagopa.it"
    path: /pagopa-mbd/(.*)
    servicePort: 8080
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.30"
    limits:
      memory: "1512Mi"
      cpu: "0.80"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 6
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopambd' # required to show cloud role name in application insights
    ENV: 'prod'
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    COSMOS_URI: 'https://pagopa-p-weu-bizevents-ds-cosmos-account.documents.azure.com:443/'
    COSMOS_ENDPOINT_DISCOVERY_ENABLED: 'true'
    COSMOS_PREFERRED_REGIONS: 'North Europe'
    CACHE_REFRESH_ENABLED: 'false'
    CACHE_REFRESH_CRON: '-'
    HOME: '/tmp'
    RENDICONTAZIONI_GENERATE_ENABLED: 'true'
    RENDICONTAZIONI_GENERATE_CRON: '-'
    CLIENT_CACHE_URL: 'https://api.prod.platform.pagopa.it/api-config-cache/p/v1'
    CLIENT_CACHE_READ_TIMEOUT: "5000"
    MAX_RECORD_V_PER_FILE: "100_000"
    OTEL_SERVICE_NAME: pagopa-mbd
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envFieldRef: &envFieldRef
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    COSMOS_KEY: 'cosmos-biz-account-key'
    CLIENT_CACHE_SUBKEY: 'api-config-cache-subscription-key-string'
  keyvault:
    name: "pagopa-p-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
