microservice-chart:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-mbd
    tag: "0.2.10"
    pullPolicy: Always
  livenessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  deployment:
    create: true
    replicas: 1 # same as HPA minReplica
  providedVolumeMount:
    create: true
    folders:
      - name: firmatore
        readOnly: false
        mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 12345 #jmx-exporter
    - 8080
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weudev.nodo.internal.dev.platform.pagopa.it"
    path: /pagopa-mbd/(.*)
    servicePort: 8080
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: "919f4844-47c9-4c54-b2ec-185615bf1246"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.30"
    limits:
      memory: "1024Mi"
      cpu: "0.50"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    APP_NAME: "pagopambd"
    APP_ENVIRONMENT: "dev"
    WEBSITE_SITE_NAME: 'pagopambd' # required to show cloud role name in application insights
    ENV: 'dev'
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    COSMOS_URI: 'https://pagopa-d-weu-bizevents-ds-cosmos-account.documents.azure.com:443/'
    COSMOS_ENDPOINT_DISCOVERY_ENABLED: 'true'
    COSMOS_PREFERRED_REGIONS: 'North Europe'
    CACHE_REFRESH_ENABLED: 'false'
    CACHE_REFRESH_CRON: '-'
    HOME: '/mnt/file-azure/firmatore/SID-Flussi-e-bollo/SID_cartelle/file_da_predisporre/'
    RENDICONTAZIONI_GENERATE_ENABLED: 'true'
    RENDICONTAZIONI_GENERATE_CRON: '-'
    RENDICONTAZIONI_MAX_ATTEMPTS: '3'
    RENDICONTAZIONI_DELAY: '2000'
    RENDICONTAZIONI_MULTIPLIER: '2.0'
    CLIENT_CACHE_URL: 'https://api.dev.platform.pagopa.it/api-config-cache/p/v1'
    CLIENT_CACHE_READ_TIMEOUT: "5000"
    MAX_RECORD_V_PER_FILE: "100"
    MAX_STAMPS_FOR_RECORD_V: "10"
    OTEL_SERVICE_NAME: pagopa-mbd
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=dev"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envFieldRef: &envFieldRef
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    COSMOS_KEY: 'cosmos-biz-account-key'
    CLIENT_CACHE_SUBKEY: 'api-config-cache-subscription-key-string'
    azurestorageaccountname: "azurestorageaccountname"
    azurestorageaccountkey: "azurestorageaccountkey"
  keyvault:
    name: "pagopa-d-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - 'user'
  canaryDelivery:
    create: false
# https://github.com/pagopa/pagopa-firmatore/pull/9    
runflussi-cron: # >>> CRON #1 runflussi.sh
  namespace: "nodo"
  schedule: "0 2 * * *"
  suspend: true
  timeZone: "Europe/Rome"
  successfulJobsHistoryLimit: "1"
  image:
    repository: openjdk
    tag: 8-jdk
    pullPolicy: Always
  command: ["/bin/bash", "-c", "/mnt/file-azure/firmatore/scripts/runflussi.sh"]
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  providedVolumeMount:
    create: true
    folders:
      - name: firmatore
        readOnly: false
        mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false # ln
    capabilities:
      drop:
        - all
  envConfig:
    BASE_MNT: "/mnt/file-azure/firmatore/"
    FLUSSI_DIR: "/mnt/file-azure/firmatore/SID-Flussi-e-bollo"
  envSecrets:
    azurestorageaccountname: "azurestorageaccountname"
    azurestorageaccountkey: "azurestorageaccountkey"
  keyvault:
    name: "pagopa-d-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: "919f4844-47c9-4c54-b2ec-185615bf1246"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "gps"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
renametransfer-cron: # >>> CRON #2 renametransfer.sh
  namespace: "nodo"
  schedule: "0 3 * * *"
  suspend: true
  timeZone: "Europe/Rome"
  successfulJobsHistoryLimit: "1"
  image:
    repository: openjdk
    tag: 8-jdk
    pullPolicy: Always
  command: ["/bin/bash", "-c", "/mnt/file-azure/firmatore/scripts/renametransfer.sh"]
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  providedVolumeMount:
    create: true
    folders:
      - name: firmatore
        readOnly: false
        mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false # ln
    capabilities:
      drop:
        - all
  envConfig:
    BASE_MNT: "/mnt/file-azure/firmatore/"
    FLUSSI_DIR: "/mnt/file-azure/firmatore/SID-Flussi-e-bollo"
    SFTP_USERNAME: "pagopa_pgsg"
    SFTP_HOST: "sftp1.public.pdnd.pagopa.it"
    SFTP_PORT: "22"
  envSecrets:
    azurestorageaccountname: "azurestorageaccountname"
    azurestorageaccountkey: "azurestorageaccountkey"
    SFTP_PEM_KEY: "rmbd-sftp-pem-key"
  keyvault:
    name: "pagopa-d-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: "919f4844-47c9-4c54-b2ec-185615bf1246"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "gps"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
getelabricevute-cron: # >>> CRON #3 get-elab-ricevute.sh
  namespace: "nodo"
  schedule: "30 09 * * *"
  suspend: true
  timeZone: "Europe/Rome"
  successfulJobsHistoryLimit: "1"
  image:
    repository: openjdk
    tag: 8-jdk
    pullPolicy: Always
  command: ["/bin/bash", "-c", "/mnt/file-azure/firmatore/scripts/get-elab-ricevute.sh"]
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  providedVolumeMount:
    create: true
    folders:
      - name: firmatore
        readOnly: false
        mountOptions: "dir_mode=0777,file_mode=0777,cache=strict,actimeo=30"
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false # ln
    capabilities:
      drop:
        - all
  envConfig:
    BASE_MNT: "/mnt/file-azure/firmatore/"
    FLUSSI_DIR: "/mnt/file-azure/firmatore/SID-Flussi-e-bollo"
    SFTP_USERNAME: "pagopa_pgsg"
    SFTP_HOST: "sftp1.public.pdnd.pagopa.it"
    SFTP_PORT: "22"
  envSecrets:
    azurestorageaccountname: "azurestorageaccountname"
    azurestorageaccountkey: "azurestorageaccountkey"
    SFTP_PEM_KEY: "rmbd-sftp-pem-key"
  keyvault:
    name: "pagopa-d-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  serviceAccount:
    name: "nodo-workload-identity"
  azure:
    workloadIdentityClientId: "919f4844-47c9-4c54-b2ec-185615bf1246"
  tolerations:
    - key: dedicated
      operator: Equal
      value: "gps"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
